language: objective-c
osx_image: xcode61
xcode_project: AeroGearJsonSZ.xcodeproj
xcode_scheme: AeroGearJsonSZ
xcode_sdk: iphonesimulator

notifications:
  irc: "irc.freenode.org#aerogear"

branches:
  only:
    - master
